# Generated by Django 2.0.4 on 2018-04-20 23:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('desc', models.TextField()),
                ('email', models.EmailField(max_length=200)),
                ('website', models.TextField()),
                ('category', models.ManyToManyField(to='page.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Leader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('fun', models.IntegerField(choices=[(1, 'Yes'), (0, 'No')])),
                ('meaningful', models.IntegerField(validators=[django.core.validators.MaxValueValidator(1), django.core.validators.MinValueValidator(0)])),
                ('stars', models.IntegerField(validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)])),
                ('CBI', models.CharField(max_length=200)),
                ('rating', models.IntegerField(default='0')),
            ],
        ),
        migrations.AddField(
            model_name='club',
            name='leaders',
            field=models.ManyToManyField(to='page.Leader'),
        ),
        migrations.AddField(
            model_name='club',
            name='reviews',
            field=models.ManyToManyField(to='page.Review'),
        ),
    ]
