# Generated by Django 2.0.4 on 2018-04-20 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0008_auto_20180420_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='fun_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='club',
            name='meaning_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='club',
            name='total_stars',
            field=models.IntegerField(default=0),
        ),
    ]
