# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-06 20:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0002_auto_20180406_1335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='category',
        ),
        migrations.AddField(
            model_name='club',
            name='category',
            field=models.ManyToManyField(to='page.Category'),
        ),
        migrations.AlterField(
            model_name='club',
            name='email',
            field=models.EmailField(max_length=200),
        ),
        migrations.RemoveField(
            model_name='club',
            name='leaders',
        ),
        migrations.AddField(
            model_name='club',
            name='leaders',
            field=models.ManyToManyField(to='page.Leader'),
        ),
        migrations.AlterField(
            model_name='club',
            name='website',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='leader',
            name='email',
            field=models.EmailField(max_length=100),
        ),
    ]
