# Generated by Django 2.0.4 on 2018-04-24 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0004_auto_20180422_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='total_stars',
            field=models.FloatField(default=0),
        ),
    ]
