# Generated by Django 2.0.4 on 2018-04-24 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0005_auto_20180423_1951'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='picture1',
            field=models.ImageField(default='pic_folder/None/no-img.jpg', upload_to='pic_folder/'),
        ),
    ]
