# Generated by Django 2.0.4 on 2018-04-26 04:29

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('page', '0006_auto_20180424_1914'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('netid', models.CharField(max_length=50)),
                ('is_club', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='club',
            name='leaders',
        ),
        migrations.RemoveField(
            model_name='club',
            name='reviews',
        ),
        migrations.AddField(
            model_name='leader',
            name='club',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='page.Club'),
        ),
        migrations.AddField(
            model_name='review',
            name='club',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='page.Club'),
        ),
        migrations.AlterField(
            model_name='review',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='review',
            name='fun',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(1), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='student',
            name='club_interviews_reviewed',
            field=models.ManyToManyField(related_name='interviews', to='page.Club'),
        ),
        migrations.AddField(
            model_name='student',
            name='clubs_liked',
            field=models.ManyToManyField(related_name='likes', to='page.Club'),
        ),
        migrations.AddField(
            model_name='student',
            name='clubs_reviewed',
            field=models.ManyToManyField(related_name='submissions', to='page.Club'),
        ),
        migrations.AddField(
            model_name='student',
            name='review_votes',
            field=models.ManyToManyField(related_name='votes', to='page.Review'),
        ),
        migrations.AddField(
            model_name='student',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='review',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='page.Student'),
        ),
    ]
