# Generated by Django 2.0.4 on 2018-04-25 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0006_club_picture1'),
        ('page', '0007_auto_20180424_2021'),
    ]

    operations = [
    ]
