# Generated by Django 2.0.4 on 2018-04-25 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0008_merge_20180424_2030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='picture1',
        ),
    ]
