# Generated by Django 2.0.4 on 2018-04-27 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0007_auto_20180426_0029'),
        ('page', '0009_remove_club_picture1'),
    ]

    operations = [
    ]
