# Generated by Django 2.0.4 on 2018-04-27 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0011_auto_20180426_2056'),
        ('page', '0010_merge_20180426_2033'),
    ]

    operations = [
    ]
