# Generated by Django 2.0.4 on 2018-04-28 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0013_auto_20180428_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='photo',
            field=models.ImageField(default='static/images/300x100.jpg', upload_to='static/images'),
        ),
    ]
