# Generated by Django 2.0.4 on 2018-04-28 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0014_auto_20180428_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='photo',
            field=models.ImageField(upload_to='static/images'),
        ),
    ]
