# Generated by Django 2.0.4 on 2018-04-28 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0015_auto_20180428_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='photo',
            field=models.ImageField(upload_to=''),
        ),
    ]
