# Generated by Django 2.0.4 on 2018-04-28 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0017_remove_club_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='photo',
            field=models.ImageField(null=True, upload_to='gallery'),
        ),
    ]
