# Generated by Django 2.0.4 on 2018-04-28 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0018_club_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='club',
            old_name='photo',
            new_name='photo1',
        ),
        migrations.AddField(
            model_name='club',
            name='photo2',
            field=models.ImageField(null=True, upload_to='gallery'),
        ),
        migrations.AddField(
            model_name='club',
            name='photo3',
            field=models.ImageField(null=True, upload_to='gallery'),
        ),
    ]
