# Generated by Django 2.0.4 on 2018-04-29 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0019_auto_20180428_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='photo1',
            field=models.ImageField(blank=True, null=True, upload_to='gallery'),
        ),
        migrations.AlterField(
            model_name='club',
            name='photo2',
            field=models.ImageField(blank=True, null=True, upload_to='gallery'),
        ),
        migrations.AlterField(
            model_name='club',
            name='photo3',
            field=models.ImageField(blank=True, null=True, upload_to='gallery'),
        ),
    ]
