# Generated by Django 2.0.4 on 2018-04-29 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0020_auto_20180429_1841'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='is_club',
        ),
    ]
