# Generated by Django 2.0.4 on 2018-04-29 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0021_remove_student_is_club'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='clubs_interested',
            field=models.ManyToManyField(related_name='interested', to='page.Club'),
        ),
    ]
