# Generated by Django 2.0.4 on 2018-05-01 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0023_interview'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='hard_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='club',
            name='positive_count',
            field=models.IntegerField(default=0),
        ),
    ]
