# Generated by Django 2.0.4 on 2018-05-03 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0030_auto_20180502_2002'),
        ('page', '0031_auto_20180502_2001'),
    ]

    operations = [
    ]
