# Generated by Django 2.0.4 on 2018-05-08 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0033_auto_20180506_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='category',
            field=models.ManyToManyField(blank=True, null=True, to='page.Category'),
        ),
        migrations.AlterField(
            model_name='club',
            name='desc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='club',
            name='email',
            field=models.EmailField(blank=True, max_length=200, null=True),
        ),
    ]
