# Generated by Django 2.0.4 on 2018-05-11 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0036_auto_20180510_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='email',
            field=models.EmailField(max_length=200),
        ),
    ]
