# Generated by Django 2.0.4 on 2018-05-13 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0037_auto_20180511_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='name',
            field=models.CharField(max_length=80),
        ),
    ]
