# Generated by Django 2.0.4 on 2018-05-13 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0037_auto_20180511_1258'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='review_votes',
        ),
        migrations.AddField(
            model_name='student',
            name='review_downvotes',
            field=models.ManyToManyField(blank=True, related_name='downvotes', to='page.Review'),
        ),
        migrations.AddField(
            model_name='student',
            name='review_upvotes',
            field=models.ManyToManyField(blank=True, related_name='upvotes', to='page.Review'),
        ),
    ]
