# Generated by Django 2.0.4 on 2018-05-13 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0039_auto_20180512_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='desc',
            field=models.TextField(blank=True, max_length=1300, null=True),
        ),
    ]
