# Generated by Django 2.0.4 on 2018-05-13 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0046_auto_20180512_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='desc',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='club',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
