# Generated by Django 2.0.4 on 2018-05-13 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0047_auto_20180512_2255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='desc',
            field=models.TextField(blank=True, max_length=1300, null=True),
        ),
        migrations.AlterField(
            model_name='club',
            name='email',
            field=models.EmailField(max_length=30),
        ),
        migrations.AlterField(
            model_name='club',
            name='name',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='club',
            name='website',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='interview',
            name='text',
            field=models.TextField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='leader',
            name='email',
            field=models.EmailField(max_length=40),
        ),
        migrations.AlterField(
            model_name='leader',
            name='name',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='leader',
            name='title',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='review',
            name='text',
            field=models.TextField(max_length=2000),
        ),
    ]
