# Generated by Django 2.0.4 on 2018-05-13 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0038_auto_20180513_0336'),
        ('page', '0049_auto_20180512_2303'),
    ]

    operations = [
    ]
