# Generated by Django 2.0.4 on 2018-05-13 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0051_auto_20180513_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leader',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
